# 项目启动端口
server:
  address: :2002
  # debug模式
  model: debug
  # release模式
  # model: release

# 数据库配置
db:
  dialects: mysql
  host: 47.100.97.238
  port: 3306
  db: admin-go-api
  username: root
  password: GCW1017+
  charset: utf8
  # 最大空闲数
  maxIdle: 50
  # 最大连接数
  maxOpen: 150

# redis配置
redis:
  address: 47.100.97.238:6379
  password: 123456

# 图片地址和ip
imageSettings:
  # 本地磁盘地址
  uploadDir: /admin-go-api/upload/
  # 本地ip地址
  imageHost: http://localhost:2002

# log日志配置
log:
  path: ./log
  name: sys
  # 输出到控制台
  model: console
  # 输出到文件
  # model: file
